//
// Created by andras on 2017.11.15..
//

#ifndef STRATEGO_UIELEMENT_H
#define STRATEGO_UIELEMENT_H

enum class UIElement {
    BACKGROUND,
    FIELD_HIGHLIGHT,
    BLUE_CARD_BACK, RED_CARD_BACK,
    RESTART_BTN, RESTART_BTN_PRESSED, EXIT_BTN, EXIT_BTN_PRESSED
};

#endif //STRATEGO_UIELEMENT_H
